In [8]:
# store start time to get execution time of entire script
import time
start_time = time.time()

In [9]:
# helper functions for displaying table data

import numpy as np
from IPython.display import display_html

# n is the number of columns to display data in
def display_side_by_side(series_obj, n):
    df = pd.DataFrame(series_obj)
    partition = int(round(len(df) / n))
    lower_bound = 0
    upper_bound = partition
    args = []
    for i in range(n):
        args.append(df[lower_bound:upper_bound])
        lower_bound += partition
        upper_bound += partition
    helper(args)

def helper(args):
    html_str=''
    for df in args:
        html_str+=df.to_html()
    display_html(html_str.replace('table','table style="display:inline"'),raw=True)

In [10]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import csv

df = pd.read_csv('../data/OP_STIM_ML_JUN192020_imputed.csv')
df.head()

,ID,State,City,agyaddr,xobsyr_0,female,nonwhite,unemplmt,prsatx,gvsg,CWSg_0,srprobg,dssg_0,epsg_0,adhdg_0,cdsg_0,cjsig_0,lrig_0,srig_0,SESg_0,r4ag_0,primsev,B2a_0,SUDSy_0,homeless_0,pssig_0,rerig_0,ncar,press,TRIg_0,PYS9Sx,PYS9Sxg,FrstUseD,loc,Raceg4,Illicit_Cens,Illicit_Days,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,primsev_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sx_cd,PYS9Sxg_cd
0,3819,AZ,Tucson,3130 E Broadway Blvd,2005,No,No,Yes,Yes,High,Low,Moderate,High,Moderate,High,Moderate,Moderate,Moderate,Moderate,High Self-Efficacy,None,amphetamines,11,6.0,No,NaN,NaN,no,NaN,Low,0.0,Subclinical (0-1 sx),366,Early Intervention,White/Caucasian,1,363,2,2,3,1,3,2,3,2,2,2,2,1,1,2,6,1,1,1,0,1
1,857,OH,Cleveland,1276 West Third St. #400,2005,No,No,no,No,High,Low,Low,Moderate,Moderate,Moderate,Moderate,Low,Moderate,High,High Self-Efficacy,Moderate,alcohol,13,0.0,No,NaN,NaN,Yes,NaN,Low,0.0,Subclinical (0-1 sx),366,Early Intervention,White/Caucasian,1,365,1,1,3,1,2,2,2,2,1,2,3,1,2,1,0,1,2,1,0,1
2,929,OH,Cleveland,1276 West Third St. #400,2006,No,No,no,No,Moderate,Low,Moderate,Low,Moderate,Low,Moderate,Moderate,Low,Moderate,High Self-Efficacy,High,alcohol,13,3.0,No,NaN,NaN,no,NaN,Moderate,0.0,Subclinical (0-1 sx),366,Early Intervention,White/Caucasian,1,354,1,1,2,1,1,2,1,2,2,1,2,1,3,1,3,1,1,2,0,1
3,951,OH,Cleveland,1276 West Third St. #400,2006,No,No,no,No,Low,Low,Moderate,Low,Low,Low,Low,Moderate,Low,Moderate,High Self-Efficacy,High,marijuana,13,2.0,No,NaN,NaN,no,NaN,Moderate,0.0,Subclinical (0-1 sx),366,Early Intervention,White/Caucasian,2,365,1,1,1,1,1,1,1,1,2,1,2,1,3,3,2,1,1,2,0,1
4,1032,OH,Cleveland,1276 West Third St. #400,2006,No,No,no,No,High,Low,Moderate,Moderate,Moderate,Moderate,Moderate,Low,High,Moderate,High Self-Efficacy,High,marijuana,13,2.0,No,NaN,NaN,Yes,NaN,Moderate,0.0,Subclinical (0-1 sx),366,Early Intervention,White/Caucasian,2,365,1,1,3,1,2,2,2,2,1,3,2,1,3,3,2,1,2,2,0,1

In [11]:
df['SUDSy_0_cd'].value_counts()

0     5941
1     2514
2     2252
3     2065
11    1947
4     1925
10    1834
6     1688
9     1606
5     1599
7     1558
8     1539
Name: SUDSy_0_cd, dtype: int64

In [12]:
# group SUDSy_0_cd
df['SUDSy_0_cd'] += 10 # add 10 to prevent overlapping replacement

df['SUDSy_0_cd'] = np.where(df['SUDSy_0_cd'].between(10,11), 1, df['SUDSy_0_cd'])
df['SUDSy_0_cd'] = np.where(df['SUDSy_0_cd'].between(12,15), 2, df['SUDSy_0_cd'])
df['SUDSy_0_cd'] = np.where(df['SUDSy_0_cd'].between(16,22), 3, df['SUDSy_0_cd'])

df['SUDSy_0_cd'].value_counts()

3    10172
1     8455
2     7841
Name: SUDSy_0_cd, dtype: int64

In [13]:
df = df[df.B2a_0 <= 29]
np.unique(df['B2a_0']).tolist() # confirm that this dataset contains adolescents AND young adults

[10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [14]:
cols_to_use = ['ID','State','City','agyaddr','xobsyr_0','B2a_0','Illicit_Days','Illicit_Cens']

unimputed_cols_to_use = ['female','nonwhite','primsev','loc']

# keep imputed columns 
imputed_cols_to_use = ['unemplmt_cd','prsatx_cd','gvsg_cd','CWSg_0_cd',
                       'dssg_0_cd','epsg_0_cd','adhdg_0_cd','cdsg_0_cd','cjsig_0_cd','lrig_0_cd','srig_0_cd',
                       'SESg_0_cd','r4ag_0_cd','SUDSy_0_cd','homeless_0_cd','ncar_cd','TRIg_0_cd','PYS9Sxg_cd']

df = df[cols_to_use + unimputed_cols_to_use + imputed_cols_to_use]
df.head()

,ID,State,City,agyaddr,xobsyr_0,B2a_0,Illicit_Days,Illicit_Cens,female,nonwhite,primsev,loc,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd
0,3819,AZ,Tucson,3130 E Broadway Blvd,2005,11,363,1,No,No,amphetamines,Early Intervention,2,2,3,1,3,2,3,2,2,2,2,1,1,3,1,1,1,1
1,857,OH,Cleveland,1276 West Third St. #400,2005,13,365,1,No,No,alcohol,Early Intervention,1,1,3,1,2,2,2,2,1,2,3,1,2,1,1,2,1,1
2,929,OH,Cleveland,1276 West Third St. #400,2006,13,354,1,No,No,alcohol,Early Intervention,1,1,2,1,1,2,1,2,2,1,2,1,3,2,1,1,2,1
3,951,OH,Cleveland,1276 West Third St. #400,2006,13,365,2,No,No,marijuana,Early Intervention,1,1,1,1,1,1,1,1,2,1,2,1,3,2,1,1,2,1
4,1032,OH,Cleveland,1276 West Third St. #400,2006,13,365,2,No,No,marijuana,Early Intervention,1,1,3,1,2,2,2,2,1,3,2,1,3,2,1,2,2,1

In [15]:
df.shape

(24300, 30)

In [16]:
from tqdm.notebook import tqdm

# ad hoc way of getting censoring to be correct
df['Illicit_Cens'] += 3 # add 3 to prevent overlapping replacement
# no relapse and censored data needs to be censored in the overall model
df.replace({'Illicit_Cens': {3: 1, 4: 0, 5:0}}, inplace=True) # 3 == relapsed, 4 == no relapse, 5 == censored

df['Illicit_Cens'].value_counts()

0    17149
1     7151
Name: Illicit_Cens, dtype: int64

In [17]:
df.replace(to_replace=['Yes', 'No'], value=[1, 0], inplace=True)

In [18]:
cat_vars = ['primsev']

for var in cat_vars:
    # one-hot encode categorical variables
    one_hot = pd.get_dummies(df[var], prefix=var)
    df = df.drop(var, axis = 1)
    df = df.join(one_hot)

df.rename(columns={'primsev_Other drug':'primsev_other'}, inplace=True)
df.head()

,ID,State,City,agyaddr,xobsyr_0,B2a_0,Illicit_Days,Illicit_Cens,female,nonwhite,loc,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids
0,3819,AZ,Tucson,3130 E Broadway Blvd,2005,11,363,0,0,0,Early Intervention,2,2,3,1,3,2,3,2,2,2,2,1,1,3,1,1,1,1,0,0,1,0,0,0
1,857,OH,Cleveland,1276 West Third St. #400,2005,13,365,0,0,0,Early Intervention,1,1,3,1,2,2,2,2,1,2,3,1,2,1,1,2,1,1,0,1,0,0,0,0
2,929,OH,Cleveland,1276 West Third St. #400,2006,13,354,0,0,0,Early Intervention,1,1,2,1,1,2,1,2,2,1,2,1,3,2,1,1,2,1,0,1,0,0,0,0
3,951,OH,Cleveland,1276 West Third St. #400,2006,13,365,0,0,0,Early Intervention,1,1,1,1,1,1,1,1,2,1,2,1,3,2,1,1,2,1,0,0,0,0,1,0
4,1032,OH,Cleveland,1276 West Third St. #400,2006,13,365,0,0,0,Early Intervention,1,1,3,1,2,2,2,2,1,3,2,1,3,2,1,2,2,1,0,0,0,0,1,0

In [19]:
# create grouped age variable based on Mike's suggestions
# >15, 15-18, <18
df['B2a_0g'] = np.nan
for i,row in tqdm(df.iterrows(), total=df.shape[0]):
    age = row['B2a_0']
    if age < 15:
        df.set_value(i, 'B2a_0g', 0)
    elif age < 18:
        df.set_value(i, 'B2a_0g', 1)
    else:
        df.set_value(i, 'B2a_0g', 2)

df['B2a_0g'] = df['B2a_0g'].astype(int)
df.drop(columns=['B2a_0'], inplace=True)
df.head()

HBox(children=(IntProgress(value=0, max=24300), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  # This is added back by InteractiveShellApp.init_path()

,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,loc,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g
0,3819,AZ,Tucson,3130 E Broadway Blvd,2005,363,0,0,0,Early Intervention,2,2,3,1,3,2,3,2,2,2,2,1,1,3,1,1,1,1,0,0,1,0,0,0,0
1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,Early Intervention,1,1,3,1,2,2,2,2,1,2,3,1,2,1,1,2,1,1,0,1,0,0,0,0,0
2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,Early Intervention,1,1,2,1,1,2,1,2,2,1,2,1,3,2,1,1,2,1,0,1,0,0,0,0,0
3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,Early Intervention,1,1,1,1,1,1,1,1,2,1,2,1,3,2,1,1,2,1,0,0,0,0,1,0,0
4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,Early Intervention,1,1,3,1,2,2,2,2,1,3,2,1,3,2,1,2,2,1,0,0,0,0,1,0,0

In [20]:
# subset data based on whether the patient lived at the clinic or not
values = ['STR','MTR','LTR','Corrections']

df = df[~df['loc'].isin(values)]

df.drop(columns=['loc'], inplace=True)
df.shape

(21939, 34)

In [21]:
# subtract 1 from imputed columns to keep levels same as rest of dataset
for col in df.columns:
    if '_cd' in col and col != 'SUDSy_0_cd':
        df[col] = df[col] - 1

df.head()

,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g
0,3819,AZ,Tucson,3130 E Broadway Blvd,2005,363,0,0,0,1,1,2,0,2,1,2,1,1,1,1,0,0,3,0,0,0,0,0,0,1,0,0,0,0
1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,1,1,1,1,0,1,2,0,1,1,0,1,0,0,0,1,0,0,0,0,0
2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,0,1,0,1,1,0,1,0,2,2,0,0,1,0,0,1,0,0,0,0,0
3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,2,2,0,0,1,0,0,0,0,0,1,0,0
4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,0,2,1,0,2,2,0,1,1,0,0,0,0,0,1,0,0

In [22]:
# merge suds_var with rest of dataset
"""suds_var = pd.read_csv('suds_var.csv')
suds_var.drop(columns=['SDSl_0'], inplace=True)
suds_var.head()"""

"suds_var = pd.read_csv('suds_var.csv')\nsuds_var.drop(columns=['SDSl_0'], inplace=True)\nsuds_var.head()"

In [23]:
"""df = df.merge(suds_var, on='ID', how='left')
df = df[df.SUDSy_0 >= 0]
df.shape"""

"df = df.merge(suds_var, on='ID', how='left')\ndf = df[df.SUDSy_0 >= 0]\ndf.shape"

In [24]:
# see distribution of our predictor feature
df.hist(column='Illicit_Days', bins=21)

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x11511b208>]],
      dtype=object)

In [25]:
df = df.dropna() # remove any remaining null-valued rows

In [26]:
df.head()

,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g
0,3819,AZ,Tucson,3130 E Broadway Blvd,2005,363,0,0,0,1,1,2,0,2,1,2,1,1,1,1,0,0,3,0,0,0,0,0,0,1,0,0,0,0
1,857,OH,Cleveland,1276 West Third St. #400,2005,365,0,0,0,0,0,2,0,1,1,1,1,0,1,2,0,1,1,0,1,0,0,0,1,0,0,0,0,0
2,929,OH,Cleveland,1276 West Third St. #400,2006,354,0,0,0,0,0,1,0,0,1,0,1,1,0,1,0,2,2,0,0,1,0,0,1,0,0,0,0,0
3,951,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,2,2,0,0,1,0,0,0,0,0,1,0,0
4,1032,OH,Cleveland,1276 West Third St. #400,2006,365,0,0,0,0,0,2,0,1,1,1,1,0,2,1,0,2,2,0,1,1,0,0,0,0,0,1,0,0

In [27]:
df.shape

(21939, 34)

In [28]:
df.to_csv('../data/data_cleaned.csv')

In [29]:
# print out total notebook execution time
total_seconds = int(time.time() - start_time)
minutes = total_seconds // 60
seconds = total_seconds % 60
print("--- " + str(minutes) + " minutes " + str(seconds) + " seconds ---")

--- 0 minutes 10 seconds ---