In [299]:
# store start time to get execution time of entire script
import time
start_time = time.time()

In [300]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
import csv

df = pd.read_csv("../data/data_geocoded.csv")
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS
0,0,4,18054,VA,Lynchburg,2241 Langhorne Rd.,2008,354,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,1,1,0,0,0,0,0,1,0,1,"2241 Langhorne Rd. , L...",37.411866,-79.171371,Virginia,51680.0,5.168000e+14
1,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14
2,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14
3,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14
4,4,9,7517,CA,Santa Cruz,1080 Emeline Ave.,2006,365,0,0,0,0,1,1,0,2,2,2,1,0,2,2,1,0,3,0,0,2,0,0,1,0,0,0,0,1,"1080 Emeline Ave. , S...",36.991524,-122.016141,California,6087.0,6.087121e+13

In [301]:
df.shape

(21896, 42)

In [302]:
df = df[df.xobsyr_0 >= 2006] # remove rows from before census availability
df.shape

(16179, 42)

Add Muder Data

In [303]:
murder_data = pd.read_csv('../data/UCR-1985-2015.csv', error_bad_lines=False)
murder_data.head()

,Unnamed: 0,Agency,city,state,state_short,1985_raw_murder_num,1986_raw_murder_num,1987_raw_murder_num,1988_raw_murder_num,1989_raw_murder_num,1990_raw_murder_num,1991_raw_murder_num,1992_raw_murder_num,1993_raw_murder_num,1994_raw_murder_num,1995_raw_murder_num,1996_raw_murder_num,1997_raw_murder_num,1998_raw_murder_num,1999_raw_murder_num,2000_raw_murder_num,2001_raw_murder_num,2002_raw_murder_num,2003_raw_murder_num,2004_raw_murder_num,2005_raw_murder_num,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num,2013_raw_murder_num,2014_raw_murder_num,2015_raw_murder_num,1985_murder_rate,1986_murder_rate,1987_murder_rate,1988_murder_rate,1989_murder_rate,1990_murder_rate,1991_murder_rate,1992_murder_rate,1993_murder_rate,1994_murder_rate,1995_murder_rate,1996_murder_rate,1997_murder_rate,1998_murder_rate,1999_murder_rate,2000_murder_rate,2001_murder_rate,2002_murder_rate,2003_murder_rate,2004_murder_rate,2005_murder_rate,2006_murder_rate,2007_murder_rate,2008_murder_rate,2009_murder_rate,2010_murder_rate,2011_murder_rate,2012_murder_rate,2013_murder_rate,2014_murder_rate,2015_murder_rate
0,0,New York City Police Dept,New York City,New York,NY,1384.0,1582.0,1672.0,1896.0,1905.0,2245.0,2154.0,1995.0,1946.0,1561.0,1177.0,983.0,770.0,633.0,664.0,673.0,714.0,587.0,597.0,570.0,539.0,596.0,496.0,523.0,471.0,536.0,515.0,419.0,335.0,333.0,288.0,19.3,22.0,23.0,25.8,25.8,30.7,29.3,27.1,26.5,21.3,16.1,13.4,10.5,8.6,8.9,8.4,8.9,7.3,7.4,7.0,6.6,7.3,6.0,6.3,5.6,6.6,6.3,5.1,3.99,3.93,3.398656
1,1,Los Angeles Police Dept,Los Angeles,California,CA,777.0,834.0,811.0,736.0,877.0,983.0,1027.0,1094.0,1076.0,845.0,849.0,711.0,576.0,426.0,425.0,550.0,588.0,654.0,515.0,518.0,489.0,480.0,395.0,384.0,312.0,293.0,297.0,299.0,251.0,260.0,282.0,24.4,25.6,24.3,21.6,25.5,28.2,28.9,30.3,30.5,23.8,24.5,20.3,16.3,11.8,11.6,14.9,15.6,17.1,13.4,13.4,12.6,12.4,10.2,10.0,8.1,7.7,7.7,7.8,6.47,6.66,7.218235
2,2,Chicago Police Dept,Chicago,Illinois,IL,666.0,744.0,687.0,660.0,742.0,850.0,925.0,939.0,845.0,928.0,824.0,789.0,757.0,703.0,641.0,631.0,666.0,648.0,598.0,448.0,448.0,468.0,443.0,510.0,458.0,432.0,431.0,500.0,414.0,411.0,478.0,22.2,24.8,22.8,22.0,24.8,30.5,32.9,33.1,30.3,33.1,30.0,28.6,27.4,25.6,22.7,21.8,22.9,22.1,20.6,15.5,15.6,16.4,15.7,18.0,16.1,16.0,15.9,18.5,15.22,15.09,17.546945
3,3,Houston Police Dept,Houston,Texas,TX,457.0,408.0,323.0,440.0,459.0,568.0,608.0,465.0,446.0,375.0,316.0,261.0,254.0,254.0,241.0,230.0,267.0,256.0,278.0,272.0,334.0,377.0,351.0,294.0,287.0,269.0,198.0,217.0,214.0,242.0,303.0,26.2,22.9,18.6,25.5,26.8,34.8,36.5,27.4,25.9,21.3,18.2,14.7,14.1,14.1,13.3,11.8,13.4,12.5,13.6,13.3,16.3,18.2,16.2,13.1,12.6,12.8,9.2,10.0,9.81,10.90,13.649061
4,4,Philadelphia Police Dept,Philadelphia,Pennsylvania,PA,273.0,343.0,338.0,374.0,475.0,503.0,440.0,425.0,439.0,404.0,432.0,420.0,418.0,338.0,292.0,319.0,309.0,288.0,348.0,330.0,377.0,407.0,392.0,331.0,302.0,306.0,324.0,331.0,247.0,248.0,280.0,16.6,20.8,20.5,22.6,28.7,31.7,27.6,26.5,28.1,25.9,28.2,27.5,27.4,23.3,20.3,21.0,20.4,18.9,23.3,22.2,25.6,27.8,27.3,23.0,19.5,20.1,21.2,21.5,15.90,15.91,17.959517

In [304]:
raw_murder_nums = ['2006_raw_murder_num','2007_raw_murder_num','2008_raw_murder_num','2009_raw_murder_num',
                   '2010_raw_murder_num','2011_raw_murder_num','2012_raw_murder_num']

cols_to_use = ['city','state_short']
murder_data = murder_data[cols_to_use + raw_murder_nums]
murder_data.head()

,city,state_short,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num
0,New York City,NY,596.0,496.0,523.0,471.0,536.0,515.0,419.0
1,Los Angeles,CA,480.0,395.0,384.0,312.0,293.0,297.0,299.0
2,Chicago,IL,468.0,443.0,510.0,458.0,432.0,431.0,500.0
3,Houston,TX,377.0,351.0,294.0,287.0,269.0,198.0,217.0
4,Philadelphia,PA,407.0,392.0,331.0,302.0,306.0,324.0,331.0

In [305]:
murder_data.shape

(290, 9)

In [306]:
murder_data.rename(columns = {'city':'City', 'state_short':'State'}, inplace=True)

In [307]:
df['City'] = df['City'].str.strip()

In [308]:
df = pd.merge(df, murder_data, on=['City', 'State'], how='left')
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num
0,0,4,18054,VA,Lynchburg,2241 Langhorne Rd.,2008,354,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,1,1,0,0,0,0,0,1,0,1,"2241 Langhorne Rd. , L...",37.411866,-79.171371,Virginia,51680.0,5.168000e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14,22.0,10.0,10.0,17.0,9.0,11.0,8.0
2,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14,110.0,123.0,115.0,99.0,80.0,71.0,93.0
3,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14,119.0,122.0,116.0,99.0,79.0,89.0,89.0
4,4,9,7517,CA,Santa Cruz,1080 Emeline Ave.,2006,365,0,0,0,0,1,1,0,2,2,2,1,0,2,2,1,0,3,0,0,2,0,0,1,0,0,0,0,1,"1080 Emeline Ave. , S...",36.991524,-122.016141,California,6087.0,6.087121e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [309]:
df.shape

(16179, 49)

In [310]:
import numpy as np

print(np.sort(df['xobsyr_0'].unique()))

[2006 2007 2008 2009 2010 2011 2012]

In [311]:
%%time
from tqdm.notebook import tqdm # used to show progress bar

# only keep the value that matches the year, set all other values to NaN

for i,row in tqdm(df.iterrows(), total=df.shape[0]):
    year = row['xobsyr_0']
    for i in range(len(raw_murder_nums)):
        if int(raw_murder_nums[i][:4]) != int(year):
            df.set_value(i, raw_murder_nums[i], np.nan)
            
df.head()

HBox(children=(IntProgress(value=0, max=16179), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if __name__ == '__main__':

CPU times: user 5.25 s, sys: 126 ms, total: 5.37 s
Wall time: 8.47 s

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS,2006_raw_murder_num,2007_raw_murder_num,2008_raw_murder_num,2009_raw_murder_num,2010_raw_murder_num,2011_raw_murder_num,2012_raw_murder_num
0,0,4,18054,VA,Lynchburg,2241 Langhorne Rd.,2008,354,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,1,1,0,0,0,0,0,1,0,1,"2241 Langhorne Rd. , L...",37.411866,-79.171371,Virginia,51680.0,5.168000e+14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14,22.0,NaN,10.0,17.0,9.0,11.0,8.0
2,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14,110.0,123.0,NaN,99.0,80.0,71.0,93.0
3,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14,119.0,122.0,116.0,NaN,79.0,89.0,89.0
4,4,9,7517,CA,Santa Cruz,1080 Emeline Ave.,2006,365,0,0,0,0,1,1,0,2,2,2,1,0,2,2,1,0,3,0,0,2,0,0,1,0,0,0,0,1,"1080 Emeline Ave. , S...",36.991524,-122.016141,California,6087.0,6.087121e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [312]:
# condense murder_num feature across years into one column

df['murder_num'] = np.nan

for i in range(len(raw_murder_nums)):
    df['murder_num'] = df['murder_num'].fillna(df[raw_murder_nums[i]])

df.drop(columns=raw_murder_nums, inplace=True) # drop extra rows after condensing murder_num feature
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS,murder_num
0,0,4,18054,VA,Lynchburg,2241 Langhorne Rd.,2008,354,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,1,1,0,0,0,0,0,1,0,1,"2241 Langhorne Rd. , L...",37.411866,-79.171371,Virginia,51680.0,5.168000e+14,NaN
1,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14,22.0
2,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14,110.0
3,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14,119.0
4,4,9,7517,CA,Santa Cruz,1080 Emeline Ave.,2006,365,0,0,0,0,1,1,0,2,2,2,1,0,2,2,1,0,3,0,0,2,0,0,1,0,0,0,0,1,"1080 Emeline Ave. , S...",36.991524,-122.016141,California,6087.0,6.087121e+13,NaN

In [313]:
low = df['murder_num'].min()
high = df['murder_num'].max()
third = (high - low) / 3

df['murder_numg'] = pd.cut(df['murder_num'], [low,low+third,low+2*third,high], labels=[0, 1, 2])
df.drop(columns='murder_num', inplace=True)
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS,murder_numg
0,0,4,18054,VA,Lynchburg,2241 Langhorne Rd.,2008,354,0,0,0,0,0,0,0,0,0,0,0,0,2,1,0,0,1,0,1,1,0,0,0,0,0,1,0,1,"2241 Langhorne Rd. , L...",37.411866,-79.171371,Virginia,51680.0,5.168000e+14,NaN
1,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14,0
2,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14,0
3,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14,0
4,4,9,7517,CA,Santa Cruz,1080 Emeline Ave.,2006,365,0,0,0,0,1,1,0,2,2,2,1,0,2,2,1,0,3,0,0,2,0,0,1,0,0,0,0,1,"1080 Emeline Ave. , S...",36.991524,-122.016141,California,6087.0,6.087121e+13,NaN

In [314]:
df.shape[0] - df['murder_numg'].isna().sum() # see how many rows have crime data

10683

In [315]:
df.dropna(subset=['murder_numg'], inplace=True) # drop rows that are missing crime data
df.shape

(10683, 43)

Add Census Data

In [316]:
# start with raw numbers, end with FIPS code and concentrated disadvantage feature
def aggregate_census_data(filename):
    df_census = pd.read_csv(filename, encoding = "ISO-8859-1")
    
    cols_to_use = ['SE_A00002_002',
                   'SE_A12003_001','SE_A12003_002',
                   'SE_A17005_001','SE_A17005_003',
                   'SE_A10014_001','SE_A10014_002',
                   'SE_A13003A_001','SE_A13003A_002','SE_A13003B_001',
                   'SE_A13003B_002','SE_A13003C_001','SE_A13003C_002',
                   'Geo_FIPS']
    df_census = df_census[cols_to_use]

    # calculate population density
    df_census.rename(columns={'SE_A00002_002':'pop_den'}, inplace=True)

    # calculate percentage of school dropouts
    df_census['%_dropout'] = df_census['SE_A12003_002'] / df_census['SE_A12003_001']
    df_census.drop(columns=['SE_A12003_001','SE_A12003_002'], inplace=True)

    # calculate percentage unemployed
    df_census['%_unemployed'] = df_census['SE_A17005_003'] / df_census['SE_A17005_001']
    df_census.drop(columns=['SE_A17005_003', 'SE_A17005_001'], inplace=True)

    # calculate percentage households with public assistance income 
    df_census['%_public_assistance'] = df_census['SE_A10014_002'] / df_census['SE_A10014_001']
    df_census.drop(columns=['SE_A10014_001', 'SE_A10014_002'], inplace=True)

    # calculate percentage living in poverty
    population_cols = ['SE_A13003A_001', 'SE_A13003B_001', 'SE_A13003C_001']
    poverty_cols = ['SE_A13003A_002', 'SE_A13003B_002', 'SE_A13003C_002']
    df_census['%_poverty'] = df_census[poverty_cols].sum(axis=1) / df_census[population_cols].sum(axis=1)
    df_census.drop(columns=(population_cols + poverty_cols), inplace=True)
    
    df_census['xobsyr_0'] = year
    return df_census

In [317]:
%%time

from functools import reduce

years = [2012, 2011, 2010, 2009, 2008, 2007, 2006] # NOTE: must be in descending order
frames = []

# collect at county level
for year in years:
    df_census = aggregate_census_data('../data/census_data/county/ACS1yr' + str(year) + 'Census.csv')
    df_census['gran'] = 0
    frames.append(df_census)

# collect at census_tract level
for year in years[:-3]:
    df_census = aggregate_census_data('../data/census_data/census_tract/ACS5yr' + str(year) + 'Census.csv')
    df_census['gran'] = 1
    frames.append(df_census)    
    
hcd = pd.concat(frames)
hcd.head()

CPU times: user 4.1 s, sys: 847 ms, total: 4.95 s
Wall time: 6.71 s

,pop_den,Geo_FIPS,%_dropout,%_unemployed,%_public_assistance,%_poverty,xobsyr_0,gran
0,120.005786,1003,NaN,0.087921,0.010490,0.140557,2012,0
1,193.600629,1015,NaN,0.153805,0.023790,0.221665,2012,0
2,109.457402,1043,NaN,0.075186,0.024197,0.197444,2012,0
3,91.468972,1049,NaN,0.081434,0.017791,0.132595,2012,0
4,130.365124,1051,NaN,0.061826,0.012887,0.129935,2012,0

In [318]:
# group raw variables 

raw_census_vars = ['pop_den', '%_dropout', '%_unemployed', '%_public_assistance', '%_poverty']

for feat in raw_census_vars:
    low = hcd[feat].min()
    high = hcd[feat].max()
    quarter = (high - low) / 4

    new_feat = feat + 'g'
    
    # separate into bottom 25%, middle 50%, and upper 25%
    hcd[new_feat] = pd.cut(hcd[feat], [low,low+quarter,low+3*quarter,high], labels=[0, 1, 2])
    hcd.drop(columns=feat, inplace=True)

hcd.head()

,Geo_FIPS,xobsyr_0,gran,pop_deng,%_dropoutg,%_unemployedg,%_public_assistanceg,%_povertyg
0,1003,2012,0,0,NaN,0,0,0
1,1015,2012,0,0,NaN,0,0,0
2,1043,2012,0,0,NaN,0,0,0
3,1049,2012,0,0,NaN,0,0,0
4,1051,2012,0,0,NaN,0,0,0

In [319]:
hcd['%_povertyg'].value_counts()

0    235043
1     53609
2       705
Name: %_povertyg, dtype: int64

In [320]:
hcd['Geo_FIPS'] = hcd['Geo_FIPS'].astype(str)
hcd.dtypes

Geo_FIPS                  object
xobsyr_0                   int64
gran                       int64
pop_deng                category
%_dropoutg              category
%_unemployedg           category
%_public_assistanceg    category
%_povertyg              category
dtype: object

In [321]:
# pull out unique county/year combinations
fips_df = df[['block_FIPS', 'county_FIPS', 'xobsyr_0', 'Address', 'lat', 'lng']]
fips_df = fips_df.drop_duplicates(subset=['Address', 'xobsyr_0'])
fips_df['block_FIPS'] = fips_df['block_FIPS'].astype(str).str[:-2] # 54.099e15 -> 540990051001055.0 -> 540990051001055
fips_df['county_FIPS'] = fips_df['county_FIPS'].astype(str).str[:-2] # 54099.0 -> 54099
fips_df.head()

,block_FIPS,county_FIPS,xobsyr_0,Address,lat,lng
1,484790016011028,48479,2007,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335
2,120310143122004,12031,2011,"2671 Huffman Blvd , J...",30.298713,-81.504950
3,480291814021007,48029,2008,"7703 Floyd Curl Drive , S...",29.513085,-98.577729
6,40190019002006,4019,2007,"P.O. Box 3308 , T...",32.225221,-110.909508
9,250173529001001,25017,2008,"349 Broadway , C...",42.370383,-71.103350

In [322]:
fips_df.shape

(319, 6)

In [323]:
from tqdm.notebook import tqdm # used to show progress bar

for i,row in tqdm(fips_df.iterrows(), total=fips_df.shape[0]):
    if len(row['block_FIPS'].strip()) != 15:
        fips_df.set_value(i, 'block_FIPS', '0' + row['block_FIPS'].strip())
    if len(row['county_FIPS'].strip()) != 5:
        fips_df.set_value(i, 'county_FIPS', '0' + row['county_FIPS'].strip())
        
fips_df = fips_df.astype(str)
fips_df.head()

HBox(children=(IntProgress(value=0, max=319), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  import sys

,block_FIPS,county_FIPS,xobsyr_0,Address,lat,lng
1,484790016011028,48479,2007,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335
2,120310143122004,12031,2011,"2671 Huffman Blvd , J...",30.298712599999998,-81.50495040000001
3,480291814021007,48029,2008,"7703 Floyd Curl Drive , S...",29.5130847,-98.57772890000001
6,040190019002006,04019,2007,"P.O. Box 3308 , T...",32.225221000000005,-110.909508
9,250173529001001,25017,2008,"349 Broadway , C...",42.3703833,-71.1033498

In [324]:
fips_df = fips_df[fips_df.xobsyr_0 >= '2006']

fips_df['gran'] = np.nan
fips_df['pop_deng'] = np.nan
fips_df['%_dropoutg'] = np.nan
fips_df['%_unemployedg'] = np.nan
fips_df['%_public_assistanceg'] = np.nan
fips_df['%_povertyg'] = np.nan

fips_df.shape

(319, 12)

In [325]:
# merge with patient location data

print('Merging at census tract level...')
for i,row in tqdm(fips_df.iterrows(), total=fips_df.shape[0]):
    try:
        block_FIPS = row['block_FIPS']
        xobsyr_0 = row['xobsyr_0']
        hcd_df = hcd[hcd.xobsyr_0 == int(xobsyr_0)]
        hcd_df = hcd_df[hcd_df.gran == 0]
        for j,r in hcd_df.iterrows():
            #print(r['xobsyr_0'], '=>', xobsyr_0, block_FIPS, '=>', r['Geo_FIPS'])
            if block_FIPS.startswith(r['Geo_FIPS']): 
                #print('here!!')
                fips_df.set_value(i, 'gran', 0)
                fips_df.set_value(i, 'pop_deng', r['pop_deng'])
                fips_df.set_value(i, '%_dropoutg', r['%_dropoutg'])
                fips_df.set_value(i, '%_unemployedg', r['%_unemployedg'])
                fips_df.set_value(i, '%_public_assistanceg', r['%_public_assistanceg'])
                fips_df.set_value(i, '%_povertyg', r['%_povertyg'])
                break
    except Exception as e:
        print('Error with line ' + str(i), e)
            
fips_df.head()

Merging at census tract level...

HBox(children=(IntProgress(value=0, max=319), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  from ipykernel import kernelapp as app
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

,block_FIPS,county_FIPS,xobsyr_0,Address,lat,lng,gran,pop_deng,%_dropoutg,%_unemployedg,%_public_assistanceg,%_povertyg
1,484790016011028,48479,2007,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,0.0,0.0,0.0,0.0,0.0,1.0
2,120310143122004,12031,2011,"2671 Huffman Blvd , J...",30.298712599999998,-81.50495040000001,0.0,0.0,0.0,0.0,0.0,0.0
3,480291814021007,48029,2008,"7703 Floyd Curl Drive , S...",29.5130847,-98.57772890000001,0.0,0.0,0.0,0.0,0.0,0.0
6,040190019002006,04019,2007,"P.O. Box 3308 , T...",32.225221000000005,-110.909508,NaN,NaN,NaN,NaN,NaN,NaN
9,250173529001001,25017,2008,"349 Broadway , C...",42.3703833,-71.1033498,0.0,0.0,0.0,0.0,0.0,0.0

In [326]:
fips_df.shape[0] - fips_df['gran'].isna().sum() # see how many rows have census data

181

In [327]:
print('Merging remaining with county level data...')
for i,row in tqdm(fips_df.iterrows(), total=fips_df.shape[0]):
    try:
        if pd.isna(row['gran']): # if not filled by block_FIPS
            #print('here!', row['gran'])
            county_FIPS = row['county_FIPS']
            xobsyr_0 = row['xobsyr_0']
            hcd_df = hcd[hcd.xobsyr_0 == int(xobsyr_0)]
            hcd_df = hcd_df[hcd_df.gran == 0]
            for j,r in hcd_df.iterrows():
                #print(county_FIPS, '=>', r['Geo_FIPS'])
                try:
                    if int(r['Geo_FIPS']) == int(county_FIPS): 
                        #print('here!!', r['Geo_FIPS'], '==', county_FIPS)
                        fips_df.set_value(i, 'gran', 1)
                        fips_df.set_value(i, 'pop_deng', r['pop_deng'])
                        fips_df.set_value(i, '%_dropoutg', r['%_dropoutg'])
                        fips_df.set_value(i, '%_unemployedg', r['%_unemployedg'])
                        fips_df.set_value(i, '%_public_assistanceg', r['%_public_assistanceg'])
                        fips_df.set_value(i, '%_povertyg', r['%_povertyg'])
                        break
                except Exception as e:
                    print('Error comparing', r['Geo_FIPS'], 'with', county_FIPS)
    except Exception as e:
        print('Error with line ' + i, e)

Merging remaining with county level data...

HBox(children=(IntProgress(value=0, max=319), HTML(value='')))

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  from ipykernel import kernelapp as app
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  app.launch_new_instance()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:19: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:20: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [328]:
fips_df.shape[0] - fips_df['gran'].isna().sum() # see how many addresses have census data

319

In [329]:
from scipy.spatial.distance import cdist

def closest_point(point, points):
    """ Find closest point from a list of points. """
    return points[cdist([point], points).argmin()]

def match_value(df, col1, x, y, col2):
    """ Match value x from col1 row to value in col2. """
    df = df[df[col1] == x] # get rows of closest center
    df['year_dist'] = abs(df['xobsyr_0'] - y)
    val = df[col][df['year_dist'].idxmin()] # impute using row that is closest year-wise
    if col2 != 'gran':
        return val
    else:
        return val + 2 # adjust gran variable to reflect vars that have imputed values

In [330]:
# impute remaining null census features with that of the closest center

fips_df['xobsyr_0'] = fips_df['xobsyr_0'].astype(int)

df1 = fips_df.dropna()
df2 = fips_df[fips_df.isnull().any(1)]

df1['point'] = [(x, y) for x,y in zip(df1['lat'], df1['lng'])]
df2['point'] = [(x, y) for x,y in zip(df2['lat'], df2['lng'])]

df2['closest'] = [closest_point(x, list(df1['point'])) for x in df2['point']]

cols_to_use = ['gran','pop_deng','%_dropoutg','%_unemployedg','%_public_assistanceg','%_povertyg']

for col in cols_to_use:
    df2[col] = [match_value(df1, 'point', x, y, col) for x,y in zip(df2['closest'], df2['xobsyr_0'])]

fips_df = pd.concat([df1, df2])
fips_df.shape

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

(319, 14)

In [331]:
fips_df['xobsyr_0'] = fips_df['xobsyr_0'].astype(int)
df = pd.merge(df, fips_df, on=['Address', 'xobsyr_0'], how='left', suffixes=('', 'DUPLICATE'))
df = df[df.columns.drop(list(df.filter(regex='DUPLICATE')))] # drop duplicate columns from the merge
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS,murder_numg,%_dropoutg,%_povertyg,%_public_assistanceg,%_unemployedg,closest,gran,point,pop_deng
0,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14,0,0.0,1.0,0.0,0.0,NaN,0.0,"(27.530608, -99.472335)",0.0
1,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14,0,0.0,0.0,0.0,0.0,NaN,0.0,"(30.298712599999998, -81.50495040000001)",0.0
2,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14,0,0.0,0.0,0.0,0.0,NaN,0.0,"(29.5130847, -98.57772890000001)",0.0
3,7,13,13054,AZ,Tucson,P.O. Box 3308,2007,365,0,0,1,1,1,2,0,0,1,1,1,2,2,2,0,1,3,0,0,0,0,0,0,1,0,0,0,1,"P.O. Box 3308 , T...",32.225221,-110.909508,Arizona,4019.0,4.019002e+13,0,0.0,0.0,0.0,0.0,NaN,1.0,"(32.225221000000005, -110.909508)",0.0
4,10,16,15206,MA,Cambridge,349 Broadway,2008,337,0,1,1,0,0,2,0,2,0,0,0,0,1,2,0,0,1,1,1,1,0,0,0,1,0,0,0,2,"349 Broadway , C...",42.370383,-71.103350,Massachusetts,25017.0,2.501735e+14,0,0.0,0.0,0.0,0.0,NaN,0.0,"(42.3703833, -71.1033498)",0.0

In [332]:
# convert PYS9Sxg_cd from 4 to 3 levels

df["PYS9Sxg_cd"].replace({2: 1, 3: 2}, inplace=True) # 0 -> 0 | 1,2 -> 1 | 3 -> 2
df["PYS9Sxg_cd"].value_counts()

0    9656
2     725
1     302
Name: PYS9Sxg_cd, dtype: int64

In [333]:
df.isna().sum() # see how much missing data remains

Unnamed: 0                 0
Unnamed: 0.1               0
ID                         0
State                      0
City                       0
agyaddr                    0
xobsyr_0                   0
Illicit_Days               0
Illicit_Cens               0
female                     0
nonwhite                   0
unemplmt_cd                0
prsatx_cd                  0
gvsg_cd                    0
CWSg_0_cd                  0
dssg_0_cd                  0
epsg_0_cd                  0
adhdg_0_cd                 0
cdsg_0_cd                  0
cjsig_0_cd                 0
lrig_0_cd                  0
srig_0_cd                  0
SESg_0_cd                  0
r4ag_0_cd                  0
SUDSy_0_cd                 0
homeless_0_cd              0
ncar_cd                    0
TRIg_0_cd                  0
PYS9Sxg_cd                 0
primsev_other              0
primsev_alcohol            0
primsev_amphetamines       0
primsev_cocaine            0
primsev_marijuana          0
primsev_opioids            0
B2a_0g                     0
Address                    0
lat                        0
lng                        0
state_name                 0
county_FIPS                0
block_FIPS                 0
murder_numg                0
%_dropoutg                 0
%_povertyg                 0
%_public_assistanceg       0
%_unemployedg              0
closest                 9745
gran                       0
point                      0
pop_deng                   0
dtype: int64

In [334]:
df.shape

(10683, 51)

In [335]:
df.head()

,Unnamed: 0,Unnamed: 0.1,ID,State,City,agyaddr,xobsyr_0,Illicit_Days,Illicit_Cens,female,nonwhite,unemplmt_cd,prsatx_cd,gvsg_cd,CWSg_0_cd,dssg_0_cd,epsg_0_cd,adhdg_0_cd,cdsg_0_cd,cjsig_0_cd,lrig_0_cd,srig_0_cd,SESg_0_cd,r4ag_0_cd,SUDSy_0_cd,homeless_0_cd,ncar_cd,TRIg_0_cd,PYS9Sxg_cd,primsev_other,primsev_alcohol,primsev_amphetamines,primsev_cocaine,primsev_marijuana,primsev_opioids,B2a_0g,Address,lat,lng,state_name,county_FIPS,block_FIPS,murder_numg,%_dropoutg,%_povertyg,%_public_assistanceg,%_unemployedg,closest,gran,point,pop_deng
0,1,6,11520,TX,Laredo,"2386 E. Saunders, Suite 2",2007,78,1,0,1,0,0,2,0,1,1,0,0,2,1,2,1,2,3,0,1,1,0,0,0,0,0,1,0,1,"2386 E. Saunders, Suite 2 , L...",27.530608,-99.472335,Texas,48479.0,4.847900e+14,0,0.0,1.0,0.0,0.0,NaN,0.0,"(27.530608, -99.472335)",0.0
1,2,7,19646,FL,Jacksonville,2671 Huffman Blvd,2011,365,0,0,1,0,0,0,0,2,1,1,0,0,1,2,0,0,1,0,1,1,0,0,1,0,0,0,0,1,"2671 Huffman Blvd , J...",30.298713,-81.504950,Florida,12031.0,1.203101e+14,0,0.0,0.0,0.0,0.0,NaN,0.0,"(30.298712599999998, -81.50495040000001)",0.0
2,3,8,11738,TX,San Antonio,7703 Floyd Curl Drive,2008,188,0,0,1,0,0,0,0,0,0,0,0,1,2,2,0,0,2,0,1,0,0,0,0,0,0,1,0,1,"7703 Floyd Curl Drive , S...",29.513085,-98.577729,Texas,48029.0,4.802918e+14,0,0.0,0.0,0.0,0.0,NaN,0.0,"(29.5130847, -98.57772890000001)",0.0
3,7,13,13054,AZ,Tucson,P.O. Box 3308,2007,365,0,0,1,1,1,2,0,0,1,1,1,2,2,2,0,1,3,0,0,0,0,0,0,1,0,0,0,1,"P.O. Box 3308 , T...",32.225221,-110.909508,Arizona,4019.0,4.019002e+13,0,0.0,0.0,0.0,0.0,NaN,1.0,"(32.225221000000005, -110.909508)",0.0
4,10,16,15206,MA,Cambridge,349 Broadway,2008,337,0,1,1,0,0,2,0,2,0,0,0,0,1,2,0,0,1,1,1,1,0,0,0,1,0,0,0,2,"349 Broadway , C...",42.370383,-71.103350,Massachusetts,25017.0,2.501735e+14,0,0.0,0.0,0.0,0.0,NaN,0.0,"(42.3703833, -71.1033498)",0.0

In [336]:
df.to_csv('../data/data_superset.csv')